# Tugas2

**DISKRITISASI**




*   Carilah data yang bertipe numerik (data klasifikasi)
*   Lakukan proses diskritisasi dengan *equal width* dan *equal frequency*
* Lakukan proses diskritisasi dengan basis *entropy*
* Kumpilkan tugas dengan link github (web statis dari jupyter book)

## **1.  Pengertian**

--> Diskritisasi yaitu proses mengubah data numerik menjadi data kategorikal

## **2. Implementasi**

 --> Diskritisasi dengan Equal Width dan Equal Frequency

- Equal width : dikritisasi yang membagi data numerik menjadi beberapa kelompok dengan lebar kelompok yang kurang    lebih sama besar.
- Equal frequency : dikritisasi yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota perkelompok yang kurang lebih sama besar.

--> Diskritisasi dengan basis Entropy

  Entropy digunakan untuk menentukan yang manakah node yang akan menjadi pemecah data latih berikutnya


  ## 3. Lakukan proses diskritisasi dengan basis *entropy*

*Entropy adalah*

*   Rumus Entropy:



$$Entropy (D_{1}) = -\sum_{i=1}^{m} Pi \log_{2} Pi$$

>*   Rumus Gain:



$$Gain(E_{new}) = E_{initial} - E_{new}$$
>*   Rumus Info:



$$Info_{A}(D) = \frac{|D_{_{1}}|}{|D|} Entropy(D_{1}) + \frac{|D_{2}|}{|D|} Entropy(D_{2})$$

Membuat sample data untuk di analisis

##**3. Implementasi Code**

In [ ]:
import pandas as pd
import numpy as np 
df = pd.read_csv('https://raw.githubusercontent.com/aisyaturradiah/datamining/gh-pages/IRIS.csv')

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# show first 15 rows
df.head(10)

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa

In [ ]:
sepal_length = df["sepal_length"]
sepal_width = df["sepal_width"]
petal_length = df["petal_length"]
petal_width = df["petal_width"]

**2. Lakukan proses diskritisasi dengan equal width dan equal frequency**



###   **Equal Width**

Untuk menghitung equal width, dibutuhkan library pandas dengan menggunakan method "cut". Buat 3 label untuk mengkategorikan batas tiap ukuran petal dan sepal dengan menggunakan small, medium, large.

### Definisi *discretization*

- Proses mengubah data bertipe data *numeric* menjadi data bertipe *categorical*
-  Diskritisasi memiliki 2 pendekatan yaitu *equal-width intervals* dan *equal-frequency intervals*
-  *equal-width intervals* adalah diskritisasi dengan lebar data yang sama
-  *equal-frequency intervals* adalah diskritisasi dengan jumlah data yang sama

#### Cut

* Cut adalah sebuah *method* pada library *pandas* untuk melakukan perhitungan *equal width intervals*


```
# Syntax
pd.cut(series, interval, right=True, label)
```

##### Sepal Width

* Equal Width Intervals lebar kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

##### Sepal Width

* Equal Width Intervals lebar kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [ ]:
# equal-width intervals

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)

sepal_width_ew_binning = pd.cut(sepal_width, amount_of_binning, True, labels)
labelled_sepal_width_ew_binning = sepal_width_ew_binning.value_counts()
interval_sepal_width_ew_binning = pd.cut(sepal_width, amount_of_binning, True).value_counts()

In [ ]:
# dataframe of sepal-width and sepal category
pd.concat((sepal_width, sepal_width_ew_binning), axis=1)

    sepal_width sepal_width
0           3.5      medium
1           3.0      medium
2           3.2      medium
3           3.1      medium
4           3.6      medium
..          ...         ...
145         3.0      medium
146         2.5       small
147         3.0      medium
148         3.4      medium
149         3.0      medium

[150 rows x 2 columns]

In [ ]:
# equal-width intervals binning with label
labelled_sepal_width_ew_binning

medium    88
small     47
large     15
Name: sepal_width, dtype: int64

In [ ]:
# equal-width intervals without label
interval_sepal_width_ew_binning

(2.8, 3.6]      88
(1.998, 2.8]    47
(3.6, 4.4]      15
Name: sepal_width, dtype: int64

##Petal Width

* Equal Width Intervals lebar mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori small
* Kategori medium
* Kategori large

In [ ]:
# equal-width intervals
labels = ["small", "medium", "large"]
amount_of_binning = len(labels)

petal_width_ew_binning = pd.cut(petal_width, amount_of_binning, True, labels)
labelled_petal_width_ew_binning = petal_width_ew_binning.value_counts()
interval_petal_width_ew_binning = pd.cut(petal_width, amount_of_binning, True).value_counts()

In [ ]:
# dataframe of petal-width and petal category
pd.concat((petal_width, petal_width_ew_binning), axis=1)

    petal_width petal_width
0           0.2       small
1           0.2       small
2           0.2       small
3           0.2       small
4           0.2       small
..          ...         ...
145         2.3       large
146         1.9       large
147         2.0       large
148         2.3       large
149         1.8       large

[150 rows x 2 columns]

In [ ]:
# equal-width intervals with label
labelled_petal_width_ew_binning

medium    54
small     50
large     46
Name: petal_width, dtype: int64

In [ ]:
# equal-width intervals without label
interval_petal_width_ew_binning

(0.9, 1.7]       54
(0.0976, 0.9]    50
(1.7, 2.5]       46
Name: petal_width, dtype: int64

##### Sepal Length

* Equal Width Intervals panjang kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori small
* Kategori medium
* Kategori large

In [ ]:
# equal-width intervals

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)

sepal_length_ew_binning = pd.cut(sepal_length, amount_of_binning, True, labels)
labelled_sepal_length_ew_binning = sepal_length_ew_binning.value_counts()
interval_sepal_length_ew_binning = pd.cut(sepal_length, amount_of_binning, True).value_counts()

In [ ]:
# dataframe of sepal-width and sepal category
pd.concat((sepal_length, sepal_length_ew_binning), axis=1)

    sepal_length sepal_length
0            5.1        small
1            4.9        small
2            4.7        small
3            4.6        small
4            5.0        small
..           ...          ...
145          6.7       medium
146          6.3       medium
147          6.5       medium
148          6.2       medium
149          5.9       medium

[150 rows x 2 columns]

In [ ]:
# equal-width intervals with label
labelled_sepal_length_ew_binning

medium    71
small     59
large     20
Name: sepal_length, dtype: int64

In [ ]:
# equal-width intervals without label
interval_sepal_length_ew_binning

(5.5, 6.7]      71
(4.296, 5.5]    59
(6.7, 7.9]      20
Name: sepal_length, dtype: int64

##### Petal Length

* Equal Width Intervals panjang mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori small
* Kategori medium
* Kategori large

In [ ]:
# equal-width intervals
labels = ["small", "medium", "large"]
amount_of_binning = len(labels)

petal_length_ew_binning = pd.cut(petal_length, amount_of_binning, True, labels)
labelled_petal_length_ew_binning = petal_length_ew_binning.value_counts()
interval_petal_length_ew_binning = pd.cut(petal_length, amount_of_binning, True).value_counts()

In [ ]:
# dataframe of petal-width and petal category
pd.concat((petal_length,petal_length_ew_binning), axis=1)

    petal_length petal_length
0            1.4        small
1            1.4        small
2            1.3        small
3            1.5        small
4            1.4        small
..           ...          ...
145          5.2        large
146          5.0        large
147          5.2        large
148          5.4        large
149          5.1        large

[150 rows x 2 columns]

In [ ]:
# equal-width intervals binning with label
labelled_petal_length_ew_binning

medium    54
small     50
large     46
Name: petal_length, dtype: int64

In [ ]:
# equal-width intervals out label
interval_petal_length_ew_binning

(2.967, 4.933]    54
(0.994, 2.967]    50
(4.933, 6.9]      46
Name: petal_length, dtype: int64

##### Data Categorycal

#### Equal Frequency
Equal Frequeny merupkan metode dikritisasi yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota per kelompok yang kurang lebih sama besar.

Untuk menghitung equal frequency, dibutuhkan library pandas dengan menggunakan method "qcut".

In [ ]:
pd.concat((petal_width_ew_binning, sepal_width_ew_binning, sepal_length_ew_binning, petal_length_ew_binning), axis=1)

    petal_width sepal_width sepal_length petal_length
0         small      medium        small        small
1         small      medium        small        small
2         small      medium        small        small
3         small      medium        small        small
4         small      medium        small        small
..          ...         ...          ...          ...
145       large      medium       medium        large
146       large       small       medium        large
147       large      medium       medium        large
148       large      medium       medium        large
149       large      medium       medium        large

[150 rows x 4 columns]

#### Qcut
* Qcut adalah sebuah *method* pada library *pandas* untuk melakukan perhitungan *equal frequency intervals*

```
# Syntax
pd.qcut(series, interval, label)
```

##### Sepal Width

* Equal Frequency Intervals lebar kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori small
* Kategori medium
* Kategori large

In [ ]:
# equal-frequency intervals

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)

sepal_width_ef_binning = pd.qcut(sepal_width, amount_of_binning, labels)
labelled_sepal_width_ef_binning = sepal_width_ef_binning.value_counts()
interval_sepal_width_ef_binning = pd.qcut(sepal_width, amount_of_binning).value_counts()

In [ ]:
# dataframe of sepal-width and sepal category
pd.concat((sepal_width, sepal_width_ef_binning), axis = 1)

    sepal_width sepal_width
0           3.5       large
1           3.0      medium
2           3.2      medium
3           3.1      medium
4           3.6       large
..          ...         ...
145         3.0      medium
146         2.5       small
147         3.0      medium
148         3.4       large
149         3.0      medium

[150 rows x 2 columns]

In [ ]:
# equal-frequency intervals binning with label
labelled_sepal_width_ef_binning

small     57
medium    51
large     42
Name: sepal_width, dtype: int64

In [ ]:
# equal-frequency intervals out label
interval_sepal_width_ef_binning

(1.999, 2.9]    57
(2.9, 3.2]      51
(3.2, 4.4]      42
Name: sepal_width, dtype: int64

##### Petal Width

* Equal Frequency Intervals lebar mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori small
* Kategori medium
* Kategori large

In [ ]:
# equal-frequency intervals

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)

petal_width_ef_binning = pd.qcut(petal_width, amount_of_binning, labels)
labelled_petal_width_ef_binning = petal_width_ef_binning.value_counts()
interval_petal_width_ef_binning = pd.qcut(petal_width, amount_of_binning).value_counts()

In [ ]:
# dataframe of petal-width and petal category
pd.concat((petal_width, petal_width_ef_binning), axis = 1)

    petal_width petal_width
0           0.2       small
1           0.2       small
2           0.2       small
3           0.2       small
4           0.2       small
..          ...         ...
145         2.3       large
146         1.9       large
147         2.0       large
148         2.3       large
149         1.8       large

[150 rows x 2 columns]

In [ ]:
# equal-frequency intervals binning with label
labelled_petal_width_ef_binning

medium    52
small     50
large     48
Name: petal_width, dtype: int64

In [ ]:
# equal-frequency intervals without label
interval_petal_width_ef_binning

(0.867, 1.6]      52
(0.099, 0.867]    50
(1.6, 2.5]        48
Name: petal_width, dtype: int64

##### Sepal Length

* Equal Frequency Intervals panjang kelopak bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori small
* Kategori medium
* Kategori large

In [ ]:
# equal-frequency intervals

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)

sepal_length_ef_binning = pd.qcut(sepal_length, amount_of_binning, labels)
labelled_sepal_length_ef_binning = sepal_length_ef_binning.value_counts()
interval_sepal_length_ef_binning = pd.qcut(sepal_length, amount_of_binning).value_counts()

In [ ]:
# dataframe of sepal-length and sepal category
pd.concat((sepal_length, sepal_length_ef_binning), axis=1)

    sepal_length sepal_length
0            5.1        small
1            4.9        small
2            4.7        small
3            4.6        small
4            5.0        small
..           ...          ...
145          6.7        large
146          6.3       medium
147          6.5        large
148          6.2       medium
149          5.9       medium

[150 rows x 2 columns]

In [ ]:
# equal-frequency intervals binning with label
labelled_sepal_length_ef_binning

medium    56
small     52
large     42
Name: sepal_length, dtype: int64

In [ ]:
# equal-frequency intervals out label
interval_sepal_length_ef_binning

(5.4, 6.3]                   56
(4.2989999999999995, 5.4]    52
(6.3, 7.9]                   42
Name: sepal_length, dtype: int64

##### Petal Length

* Equal Frequency Intervals panjang mahkota bunga Iris
* Dikelompokkan menjadi 3 kategori yaitu 
* Kategori sedikit lebar
* Kategori lebar
* Kategori sangat lebar

In [ ]:
# equal-frequency intervals

labels = ["small", "medium", "large"]
amount_of_binning = len(labels)

petal_length_ef_binning = pd.qcut(petal_length, amount_of_binning, labels)
labelled_petal_length_ef_binning = petal_length_ef_binning.value_counts()
interval_petal_length_ef_binning = pd.qcut(petal_length, amount_of_binning).value_counts()

In [ ]:
# dataframe of petal-length and petal category
pd.concat((petal_length, petal_length_ef_binning), axis=1)

    petal_length petal_length
0            1.4        small
1            1.4        small
2            1.3        small
3            1.5        small
4            1.4        small
..           ...          ...
145          5.2        large
146          5.0        large
147          5.2        large
148          5.4        large
149          5.1        large

[150 rows x 2 columns]

In [ ]:
# equal-frequency intervals binning with label
labelled_petal_length_ef_binning

medium    54
small     50
large     46
Name: petal_length, dtype: int64

In [ ]:
# equal-frequency intervals out label
interval_petal_length_ef_binning

(2.633, 4.9]      54
(0.999, 2.633]    50
(4.9, 6.9]        46
Name: petal_length, dtype: int64

##### Data Categorycal

In [ ]:
pd.concat((petal_width_ef_binning, sepal_width_ef_binning, sepal_length_ef_binning, petal_length_ef_binning), axis=1)

    petal_width sepal_width sepal_length petal_length
0         small       large        small        small
1         small      medium        small        small
2         small      medium        small        small
3         small      medium        small        small
4         small       large        small        small
..          ...         ...          ...          ...
145       large      medium        large        large
146       large       small       medium        large
147       large      medium        large        large
148       large       large       medium        large
149       large      medium       medium        large

[150 rows x 4 columns]

In [ ]:
sample = df[["sepal_length"]]
sample.describe()

       sepal_length
count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000

#### ENTROPY

Diskritisasi berbasis entropi (entropy based discretization) adalah salah satu jenis algoritma diskritisasi terawasi yang menggunakan mekanisme top- down. Tujuan dari algoritma ini adalah mendapatkan partisi yang mengandung baris data dari kelas yang sama sebanyak mungkin.

*   Rumus Entropy:



$$Entropy (D_{1}) = -\sum_{i=1}^{m} Pi \log_{2} Pi$$

>*   Rumus Gain:



$$Gain(E_{new}) = E_{initial} - E_{new}$$
>*   Rumus Info:



$$Info_{A}(D) = \frac{|D_{_{1}}|}{|D|} Entropy(D_{1}) + \frac{|D_{2}|}{|D|} Entropy(D_{2})$$

Menambahkan sempel data yang akan di hitung

In [ ]:
sample = df[["petal_width","sepal_width","sepal_length","petal_length"]]
sample.describe()

       petal_width  sepal_width  sepal_length  petal_length
count   150.000000   150.000000    150.000000    150.000000
mean      1.198667     3.054000      5.843333      3.758667
std       0.763161     0.433594      0.828066      1.764420
min       0.100000     2.000000      4.300000      1.000000
25%       0.300000     2.800000      5.100000      1.600000
50%       1.300000     3.000000      5.800000      4.350000
75%       1.800000     3.300000      6.400000      5.100000
max       2.500000     4.400000      7.900000      6.900000

Membuat category random untuk semua data

In [ ]:
np.random.seed(0)
sample["category"] = np.where(np.random.choice(2,sample.shape[0]) < 1,"A","B")
sample

     petal_width  sepal_width  sepal_length  petal_length category
0            0.2          3.5           5.1           1.4        A
1            0.2          3.0           4.9           1.4        B
2            0.2          3.2           4.7           1.3        B
3            0.2          3.1           4.6           1.5        A
4            0.2          3.6           5.0           1.4        B
..           ...          ...           ...           ...      ...
145          2.3          3.0           6.7           5.2        A
146          1.9          2.5           6.3           5.0        B
147          2.0          3.0           6.5           5.2        B
148          2.3          3.4           6.2           5.4        B
149          1.8          3.0           5.9           5.1        B

[150 rows x 5 columns]

 Dalam membuat fungsi GetOverollCategory (keseluruhan) yang digunakan untuk menghitung data keseluruhan yang nantinya digunakan untuk menghitung entropy

In [ ]:
def GetOverollCategory(col):
  group = sample.loc[:, :].groupby("category").count()
  a = group.loc["A", col]
  b = group.loc["B", col]
  return (a,b,a+b)

Dalam fungsi splitter digunakan untuk membuat split antara value yang telah ditentukan lalu mengembalikan data yang telah dipisahkan

In [ ]:
def splitter(value, col):
  #get data less and greater from value
  less = sample[sample[col] <= value]
  greater = sample[sample[col] > value]

  #calculate into category for each data
  less_group = less.loc[:, :].groupby("category").count()
  greater_group = greater.loc[:, :].groupby("category").count()

  #get value based on category
  less_category_A = less_group.loc["A",col]
  less_category_B = less_group.loc["B",col]
  greater_category_A = greater_group.loc["A",col]
  greater_category_B = greater_group.loc["B",col]

  return (
      [less_category_A, less_category_B, less_category_A + less_category_B],
      [greater_category_A, greater_category_B, greater_category_A + greater_category_B]
  )

Buat fungsi entropy untuk mencari nilai entropy

In [ ]:
def entropy (d):
  r1 = (d[0] / d[2]) * np.log2(d[0] / d[2])
  r2 = (d[1] / d[2]) * np.log2(d[1] / d[2])
  return np.sum([r1, r2]) * -1

Membuat fungsi info dan gain

In [ ]:
def info(d):
  r1 = (d[0][2] / sample.shape[0]) * entropy(d[0])
  r2 = (d[1][2] / sample.shape[0]) * entropy(d[1])
  return r1 + r2

Fungsi gain untuk menghitung selisih antara entropy awal dengan yang baru

In [ ]:
def gain(Einitial, Enew):
  return Einitial - Enew

# Petal Width

In [ ]:
#Membuat Dinitial
a = GetOverollCategory(("petal_width"))
entropy_a = entropy(a)

print(a)
print(entropy_a)

(68, 82, 150)
0.993707106604508

Melakukan beberapa fungsi split untuk mendapatkan informasi yang terbaik

* SPLIT 1 : 0.1

In [ ]:
split1 = splitter(0.1,"petal_width")
info_split1 = info(split1)
gain(entropy_a, info_split1)

0.01104847098180839

* SPLIT 2 : 1.3

In [ ]:
split2 = splitter(1.3,"petal_width")
info_split2 = info(split2)
gain(entropy_a, info_split2)

0.00021232279799998643

* SPLIT 3 : 2.4

In [ ]:
split3 = splitter(2.4,"petal_width")
info_split3 = info(split3)
gain(entropy_a, info_split3)

0.0008771143281794958

Jadi pada percobaan split atribut petal width di dapat bahwa split ke 2 dengan nilai 1.3 merupakan hasil keuntungan informasi terbaik yakni dengan hasil 0.00021232279799998643

##### Sepal Width

In [ ]:
#Membuat Dinitial
b = GetOverollCategory(("sepal_width"))
entropy_b = entropy(b)

print(b)
print(entropy_b)

(68, 82, 150)
0.993707106604508

* SPLIT 1 : 2.2

In [ ]:
split1 = splitter(2.2,"sepal_width")
info_split1 = info(split1)
gain(entropy_b, info_split1)

0.0001729324189373438

* SPLIT 2 : 3.0

In [ ]:
split2 = splitter(3.0,"sepal_width")
info_split2 = info(split2)
gain(entropy_b, info_split2)

0.0009879303562354558

* SPLIT 3 : 4.0

In [ ]:
split3 = splitter(4.0,"sepal_width")
info_split3 = info(split3)
gain(entropy_b, info_split3)

0.00271470605919788

Jadi dalam percobaan split atribut sepal width di dapati bahwa split ke 1 dengan nilai 2.2 merupakan hasil keuntungan informasi terbaik yakni dengan hasil 0.0001729324189373438

##### Petal Length

In [ ]:
#Membuat Dinitial
c = GetOverollCategory(("petal_length"))
entropy_c = entropy(c)

print(c)
print(entropy_c)

(68, 82, 150)
0.993707106604508

* SPLIT 1 : 1.2

In [ ]:
split1 = splitter(1.2,"petal_length")
info_split1 = info(split1)
gain(entropy_c, info_split1)

0.003488151753460178

* SPLIT 2 : 4.5

In [ ]:
split2 = splitter(4.5,"petal_length")
info_split2 = info(split2)
gain(entropy_c, info_split2)

0.00010279135197621692

* SPLIT 3 : 6.6

In [ ]:
split3 = splitter(6.6,"petal_length")
info_split3 = info(split3)
gain(entropy_c, info_split3)

0.0008771143281794958

Jadi dalam percobaan split atribut petal length  bahwa split ke 2 dengan nilai 4.5 merupakan hasil keuntungan informasi terbaik yakni dengan hasil 0.00010279135197621692

##### Sepal Length

In [ ]:
#Membuat Dinitial
d = GetOverollCategory(("sepal_length"))
entropy_d = entropy(d)

print(d)
print(entropy_d)

(68, 82, 150)
0.993707106604508

* SPLIT 1 : 4.5

In [ ]:
split1 = splitter(4.5,"sepal_length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.0069930419733333915

* SPLIT 2 : 5.8

In [ ]:
split2 = splitter(5.8,"sepal_length")
info_split2 = info(split2)
gain(entropy_d, info_split2)

0.0038893799103313365

* SPLIT 3 : 7.5

In [ ]:
split3 = splitter(7.5,"sepal_length")
info_split3 = info(split3)
gain(entropy_d, info_split3)

0.0017898381837971877

Jadi pada percobaan split atribut petal length di dapati bahwa split ke 3 dengan nilai 7.5 merupakan hasil keuntungan informasi terbaik yakni dengan hasil 0.0017898381837971877

Membuat Dinitial

In [ ]:
D = GetOverollCategory("sepal_length")
entropy_d = entropy(D)
print(D)
print(entropy_d)

(68, 82, 150)
0.993707106604508

Melakukan beberapa tes split untuk menari informasi yang terbaik

### *Split 1 : 4.4*

In [ ]:
split1 = splitter(4.4, "sepal_length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.003488151753460178

### *Split 2 : 5.5*

In [ ]:
split2 = splitter(5.5, "sepal_length")
info_split2 = info(split2)
gain(entropy_d, info_split2)

0.012302155146638905

### *Split 3 : 7.0*

In [ ]:
split3 = splitter(7.0, "sepal_length")
info_split3 = info(split3)
gain(entropy_d, info_split3)

0.0005490214732508658

Split terbaik yaitu split 3 yang memberikan keuntungan informasi sebesar 0.0005490214732508658 karena yang paling rendah