#Tugas 3 **K-NN Algorithm IRIS dataset**

**Algoritma k-Nearest Neighbor** merupakan algoritma supervised learning (pembelajaran terawasi)yang berfungsi untuk melakukan klasifikasi suatu data berdasarkan data pembelajaran (train data sets), yang diambil dari k tetangga terdekatnya (neares neighbors). Dengan k merupakan banyaknya tetangga terdekat.

**Tujuan dari algoritma ini yaitu** untuk mengklasifikasikan obyek baru berdasarkan atribut dan sampel-sampel dari data training

**Algoritma K-Nearest neighbor** menggunakan neighborhood classification sebagai nilai prediksi dari instance yang baru.

Berikut ini adalah cara kerja dari algoritma K-NN yaitu:



*  Tentukan jumlah tetangga yang akan dilakukan perhitungan (k), misalnya kita tentukan tiga (3) tetangga terdekat (k=5).
* Menghitung jarak setiap tetangga terhadap rumah tersebut, kemudian urutkan hasilnya berdasarkan jarak, mulai dari jarak yang terkecil ke jarak yang terbesar.
* Kemudian ambil tiga (3) (k) tetangga yang paling dekat, lalu tentukan kelas dari data baru tersebut sesuai dengan tetangga terdekatnya.

**Keuntungan dan kelemahan K-NN**



  * *Keuntungan*
    - Sangat sederhana implementasinya
    - Kuat dalam hal ruang pencarian, misalnya kelas tidak harus linier dipisahkan
    - Efektif untuk menghitung data dalam skala kecil.
    - Beberapa parameter untuk acuan yaitu jarak metrik dan *k*.




  *   *Kelemahan*

      - Perlu untuk menentukan nilai k yang optimal sehingga untuk menyatakan jumlah tetangga terdekatnya lebih mudah.
      - Biaya komputasi yang cukup tinggi karena perhitungan jarak harus dilakukan pada setiap query instance.

Melakukan load data iris, kemudian membuat variable untuk mendefinisikan data iris

In [17]:
import pandas as pd
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
#the imported dataset does not have the required column names so lets add it
colnames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']
irisdata = pd.read_csv(url, names=colnames)

In [18]:
irisdata

     sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

Selanjutnya melakukan pendefinisian variable x dan y

In [19]:
#feature matrix in a object named X
X = irisdata.values[:, 0:4]
#response vector in a object named y
y = irisdata.values[:, 4]

In [20]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)

Mengambil data latih dan data uji

In [21]:
# splitting the data into training and test sets (80:20)
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=4)

In [22]:
#shape of train and test objects
print(X_train.shape)
print(X_test.shape)

(120, 4)
(30, 4)

In [23]:
# shape of new y objects
print(y_train.shape)
print(y_test.shape)

(120,)
(30,)

Melakukan Import library KNeighborsClassifier dari sklearn

In [24]:
from sklearn.neighbors import KNeighborsClassifier

In [25]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X,y)

KNeighborsClassifier()

Malakukan pengecekan accuracy model knn

In [26]:
knn.score(X_test, y_test)

0.9666666666666667

Melakukan percobaan untuk mencari spesies yang disesuaikan dengan data baru yang telah diinputkan

In [27]:
#0 = setosa, 1=versicolor, 2=virginica
classes = {0:'Iris-setosa',1:'Iris-versicolor',2:'Iris-virginica'}

#Making prediction on some unseen data 
#predict for the below two random observations
x_new = [[5.8,	4.0,	1.2,	0.2]]
y_predict = knn.predict(x_new)

print([x_new[0],[y_predict[0]]])

[[5.8, 4.0, 1.2, 0.2], ['Iris-setosa']]